SELECT
id as transaction_line_id,
name as transaction_line_code,
date_entered as created_at,
date_modified as updated_at,
modified_user_id as updated_by,
created_by,
description,
payment_amount,
payment_method_fee,
before_discount,
discount_amount,
sponsor_amount,
loyalty_amount,
payment_method,
payment_date as transaction_date,
payment_datetime as transaction_datetime,
card_type,
is_discount,
printed_date,
status,
payment_no,
payment_id as transaction_id,
contract_id,
printed_user_id,
-- student_id,
team_id as center_id,
assigned_user_id,
pos_code,
inv_code,
parent_type,
parent_id as student_id,
is_old as is_imported,
FROM
    {{ source(
        'dotb',
        'payment_details'
    ) }}
where deleted = 0
and date_entered >='2023-01-01'