

with source as (
    select 
        json_value(data,'$.assigned_user_id') as assigned_user_id,
        safe_cast(json_value(data,'$.attendance_status') as int64) as attendance_status,
        safe_cast(json_value(data,'$.attended') as int64) as attended,
        nullif(json_value(data,'$.avg_attendance'),"") as avg_attendance,
        nullif(json_value(data,'$.cancel_by'),"") as cancel_by,
        timestamp(json_value(data,'$.cancel_date')) as cancel_date,
        nullif(json_value(data,'$.cancel_reason'),"") as cancel_reason,
        nullif(json_value(data,'$.classin_record_link'),"") as classin_record_link,
        json_value(data,'$.created_by') as created_by,
        nullif(json_value(data,'$.creator'),"") as creator,
        nullif(json_value(data,'$.customer_journey_blocked_by'),"") as customer_journey_blocked_by,
        nullif(json_value(data,'$.customer_journey_points'),"") as customer_journey_points,
        safe_cast(json_value(data,'$.customer_journey_progress') as int64) as customer_journey_progress,
        nullif(json_value(data,'$.customer_journey_score'),"") as customer_journey_score,
        timestamp(json_value(data,'$.date')) as date,
        timestamp(json_value(data,'$.date_end')) as date_end,
        timestamp(json_value(data,'$.date_entered')) as date_entered,
        timestamp(json_value(data,'$.date_modified')) as date_modified,
        timestamp(json_value(data,'$.date_start')) as date_start,
        safe_cast(json_value(data,'$.delivery_hour') as float64) as delivery_hour,
        nullif(json_value(data,'$.description'),"") as description,
        nullif(json_value(data,'$.displayed_url'),"") as displayed_url,
        safe_cast(json_value(data,'$.duration_cal') as float64) as duration_cal,
        safe_cast(json_value(data,'$.duration_hours') as int64) as duration_hours,
        safe_cast(json_value(data,'$.duration_minutes') as int64) as duration_minutes,
        safe_cast(json_value(data,'$.email_reminder_sent') as int64) as email_reminder_sent,
        safe_cast(json_value(data,'$.email_reminder_time') as int64) as email_reminder_time,
        nullif(json_value(data,'$.external_id'),"") as external_id,
        nullif(json_value(data,'$.first_duration'),"") as first_duration,
        nullif(json_value(data,'$.first_time'),"") as first_time,
        nullif(json_value(data,'$.homework'),"") as homework,
        nullif(json_value(data,'$.id'),"") as meeting_id,
        safe_cast(json_value(data,'$.is_cj_parent_activity') as int64) as is_cj_parent_activity,
        safe_cast(json_value(data,'$.is_customer_journey_activity') as int64) as is_customer_journey_activity,
        safe_cast(json_value(data,'$.is_timesheet') as int64) as is_timesheet,
        nullif(json_value(data,'$.join_url'),"") as join_url,
        nullif(json_value(data,'$.ju_class_id'),"") as class_id,
        nullif(json_value(data,'$.ju_contract_id'),"") as contract_id,
        nullif(json_value(data,'$.late_time'),"") as late_time,
        nullif(json_value(data,'$.late_time_ta1'),"") as late_time_ta1,
        nullif(json_value(data,'$.late_time_ta2'),"") as late_time_ta2,
        nullif(json_value(data,'$.lesson_number'),"") as lesson_number,
        nullif(json_value(data,'$.location'),"") as location,
        nullif(json_value(data,'$.lock_status'),"") as lock_status,
        nullif(json_value(data,'$.makeup_session_id'),"") as makeup_session_id,
        nullif(json_value(data,'$.meeting_type'),"") as meeting_type,
        json_value(data,'$.modified_user_id') as modified_user_id,
        nullif(json_value(data,'$.name'),"") as name,
        nullif(json_value(data,'$.objective_custom'),"") as objective_custom,
        nullif(json_value(data,'$.observe_note'),"") as observe_note,
        nullif(json_value(data,'$.observe_score'),"") as observe_score,
        nullif(json_value(data,'$.onl_record_link'),"") as onl_record_link,
        nullif(json_value(data,'$.outlook_id'),"") as outlook_id,
        nullif(json_value(data,'$.parent_id'),"") as parent_id,
        nullif(json_value(data,'$.parent_type'),"") as parent_type,
        nullif(json_value(data,'$.planned_absence'),"") as planned_absence,
        nullif(json_value(data,'$.recurrence_id'),"") as recurrence_id,
        nullif(json_value(data,'$.recurring_source'),"") as recurring_source,
        safe_cast(json_value(data,'$.reminder_time') as int64) as reminder_time,
        safe_cast(json_value(data,'$.repeat_count') as int64) as repeat_count,
        nullif(json_value(data,'$.repeat_days'),"") as repeat_days,
        nullif(json_value(data,'$.repeat_dow'),"") as repeat_dow,
        safe_cast(json_value(data,'$.repeat_interval') as int64) as repeat_interval,
        nullif(json_value(data,'$.repeat_ordinal'),"") as repeat_ordinal,
        nullif(json_value(data,'$.repeat_parent_id'),"") as repeat_parent_id,
        nullif(json_value(data,'$.repeat_selector'),"") as repeat_selector,
        nullif(json_value(data,'$.repeat_type'),"") as repeat_type,
        nullif(json_value(data,'$.repeat_unit'),"") as repeat_unit,
        nullif(json_value(data,'$.repeat_until'),"") as repeat_until,
        nullif(json_value(data,'$.room_id'),"") as room_id,
        safe_cast(json_value(data,'$.sequence') as int64) as sequence,
        nullif(json_value(data,'$.session_status'),"") as session_status,
        nullif(json_value(data,'$.status'),"") as status,
        nullif(json_value(data,'$.syllabus_activities'),"") as syllabus_activities,
        nullif(json_value(data,'$.syllabus_custom'),"") as syllabus_custom,
        nullif(json_value(data,'$.syllabus_default'),"") as syllabus_default,
        nullif(json_value(data,'$.syllabus_homework'),"") as syllabus_homework,
        nullif(json_value(data,'$.syllabus_id'),"") as syllabus_id,
        nullif(json_value(data,'$.syllabus_objective'),"") as syllabus_objective,
        nullif(json_value(data,'$.syllabus_topic'),"") as syllabus_topic,
        nullif(json_value(data,'$.syllabus_type'),"") as syllabus_type,
        safe_cast(json_value(data,'$.sync_timesheet') as int64) as sync_timesheet,
        safe_cast(json_value(data,'$.teaching_hour') as float64) as teaching_hour,
        nullif(json_value(data,'$.teacher_id'),"") as teacher_id,
        nullif(json_value(data,'$.teacher_cover_id'),"") as teacher_cover_id,
        nullif(json_value(data,'$.sub_teacher_id'),"") as sub_teacher_id,
        nullif(json_value(data,'$.teaching_type'),"") as teaching_type,
        nullif(json_value(data,'$.team_id'),"") as center_id,
        safe_cast(json_value(data,'$.till_hour') as float64) as till_hour,
        nullif(json_value(data,'$.time_range'),"") as time_range,
        nullif(json_value(data,'$.timesheet_id'),"") as timesheet_id,
        nullif(json_value(data,'$.topic_custom'),"") as topic_custom,
        nullif(json_value(data,'$.total_absent'),"") as total_absent,
        nullif(json_value(data,'$.total_attended'),"") as total_attended,
        nullif(json_value(data,'$.total_sent'),"") as total_sent,
        nullif(json_value(data,'$.total_student'),"") as total_student,
        nullif(json_value(data,'$.type'),"") as type,
        nullif(json_value(data,'$.week_date'),"") as week_date,
        nullif(json_value(data,'$.week_no'),"") as week_no,
    from {{ source('dotb', 'meetings') }}
        where json_value(data,'$.deleted') = '0'
    )

{{dbt_utils.deduplicate(
    relation = 'source', 
    partition_by= 'meeting_id', 
    order_by='date_modified desc'
    )
    }}