select 
id as transaction_id,
name as transaction_code,
date_entered as created_at,
date_modified as updated_at,
modified_user_id as updated_by,
created_by,
description,
payment_type as transaction_type,
payment_date as transaction_date,
settle_date,
number_of_payment,
moving_tran_out_date,
moving_tran_in_date,
sale_type,
sale_type_date,
start_study,
end_study,
class_start,
class_end,
sessions,
tuition_fee,
class_string as class_code,
level_string as level_code,
coalesce(kind_of_course,kind_of_course_string) as kind_of_course,

tuition_hours,
paid_hours,
total_hours,
payment_expired,
used_hours,
remain_hours,
note,
is_installment,
is_corporate,
is_free_book,
is_outstanding,

is_convert as is_convert_package,
refund_revenue,
use_type as consumption_type,
catch_limit as is_catch_limit,

duration_exp,
content,

primary_pay_id,
move_to_center_id,
transfer_to_student_id,
payment_out_id,
team_id as center_id,
team_set_id,
acl_team_set_id,
assigned_user_id,
user_closed_sale_id as sales_user_id,
user_pt_demo_id as pt_demo_user_id,
old_student_id,
num_month_pay,

coursefee_list,
repeat_every_pay as is_repeat_every_pay,
payment_method,
sum_paid,
sum_unpaid,
ju_class_id,
parent_type,
parent_id,
is_auto_enroll,
enroll_hours,
from {{ source('dotb','payments') }} 
where deleted = 0
and date_entered >='2023-01-01'