SELECT
    age,
    alt_address_street,
    assigned_user_id,
    birthdate as dob,
    channel,
    contact_id,
    converted,
    created_by,
    date_entered as created_at,
    date_modified as updated_at,
    date_performed as last_handover_date,
    deleted as is_deleted,
    description,
    dp_consent_last_updated,
    eng_level,
    first_call_date,
    first_call_result,
    full_lead_name,
    gender,
    guardian_name,
    id,
    last_call_date,
    last_call_result,
    last_call_status,
    last_pt_date,
    last_pt_status,
    lead_source,
    modified_user_id,
    object as lead_segment_group,
    other_mobile,
    performed_user_id as last_handover_user_id,
    phone_guardian,
    phone_mobile,
    potential,
    prefer_level,
    primary_address_city,
    primary_address_country,
    primary_address_state,
    primary_address_street,
    school_id,
    source_description,
    status,
    target,
    team_id as center_id,
    utm_agent_id,
    utm_content,
    utm_medium,
    utm_source,
FROM
    {{ source('dotb','leads') }}
where 1=1 
and date_entered >='2023-01-01'